<?php
/**
 * Created by PhpStorm.
 * User: krzysztof
 * Date: 18.02.16
 * Time: 14:24
 */
class jaszczurki {
    private $imie = '';
    private $pamiec = array();


    function __construct($x)
    {
        $this->imie = $x;
    }

    function getImie(){
        return $this->imie;
    }

    function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->imie;
    }

    function uciekaj() {
        echo "tup, tup, tup\n";
    }

    function __set($co, $wartosc) {
        $this->pamiec[$co] = $wartosc;
        echo "Nauczylem sie co to jest $co\n";
    }

    function __get($co)
    {
        // TODO: Implement __get() method.
        return $this->pamiec[$co];
    }

    function __invoke()
    {
        // TODO: Implement __invoke() method.
        echo 'oto jestem!';
    }
}

class smoki extends jaszczurki {
    function ziejeOgniem() {
        echo 'Roaaar!';
    }

    function uciekaj()
    {
        //parent::uciekaj(); // TODO: Change the autogenerated stub
        echo "bam! bam! bam\n";
    }
}

$tmp = new jaszczurki('Marian');
$abc = new smoki('Bazyli');

echo 'Ta jaszczurka to '.$tmp->getImie();

echo $tmp;
echo $abc;

$abc->ziejeOgniem();

$tmp->uciekaj();
$abc->uciekaj();

echo "<br>";
$tmp->burak = 'warzywo';
echo $tmp->burak;

$tmp();